# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 14:45
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('age', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', django.contrib.postgres.fields.jsonb.JSONField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Jedi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=10000)),
                ('answer', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academy.Planet')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.Test'),
        ),
        migrations.AddField(
            model_name='jedi',
            name='planet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.Planet'),
        ),
        migrations.AddField(
            model_name='candidateanswers',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.Test'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='jedi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academy.Jedi'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='planet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.Planet'),
        ),
    ]
