# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(max_length=10000),
        ),
    ]
