# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_remove_candidateanswers_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateanswers',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academy.Question'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidateanswers',
            name='answer',
            field=models.CharField(max_length=255),
        ),
    ]
