# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 10:10
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_auto_20171202_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateanswers',
            name='answer',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
