# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_auto_20171203_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateanswers',
            name='question',
        ),
        migrations.AddField(
            model_name='candidateanswers',
            name='test_answers',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academy.Test'),
            preserve_default=False,
        ),
    ]
