# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_auto_20171203_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidateanswers',
            old_name='test_answers',
            new_name='test',
        ),
    ]
