# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_auto_20171203_1447'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CandidateAnswers',
            new_name='CandidateAnswer',
        ),
    ]
